---
- name: create systemd service unit
  template:
    src: squid_exporter.service.j2
    dest: /etc/systemd/system/squid_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart squid_exporter
