---
- name: gather operating system variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution_file_variety | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- include: systemd.yml

- include: user.yml

- include: release.yml

- include: install.yml
  when: (not __squid_exporter_is_installed.stat.exists)

- include: configure.yml

- include: selinux.yml

- name: ensure squid_exporter is enabled on boot
  systemd:
    daemon_reload: true
    name: squid_exporter
    enabled: true
    state: started

- include_tasks: revproxy.yml
  when: squid_exporter_reverse_proxy
